<?php
// DO NOT REMOVE THIS LINE
// DO NOT REMOVE THIS LINE
// DO NOT REMOVE THIS LINE
// DO NOT REMOVE THIS LINE
// DO NOT REMOVE THIS LINE
// DO NOT REMOVE THIS LINE
class SmileyToImage
{
public static $arrayImage = array(
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/113.gif" alt="thumbs up">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/19.gif" alt="devil">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/5.gif" alt="batting eyelashes">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/20.gif" alt="crying">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/21.gif" alt="laughing">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/6.gif" alt="big hug">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/7.gif" alt="confused">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/8.gif" alt="love struck">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/9.gif" alt="blushing">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/11.gif" alt="kiss">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/12.gif" alt="broken heart">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/16.gif" alt="cool">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/18.gif" alt="whew!">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/22.gif" alt="straight face">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/24.gif" alt="rolling on the floor">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/25.gif" alt="angel">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/26.gif" alt="nerd">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/27.gif" alt="talk to the hand">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/101.gif" alt="call me">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/100.gif" alt="on the phone">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/102.gif" alt="at wits end">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/103.gif" alt="wave">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/104.gif" alt="time out">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/105.gif" alt="day dreaming">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/28.gif" alt="sleepy">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/29.gif" alt="rolling eyes">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/30.gif" alt="loser">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/31.gif" alt="sick">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/32.gif" alt="dont tell anyone">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/33.gif" alt="no talking">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/34.gif" alt="clown">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/35.gif" alt="silly">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/36.gif" alt="party">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/37.gif" alt="yawn">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/38.gif" alt="drooling">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/40.gif" alt="doh">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/41.gif" alt="applause">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/42.gif" alt="nail biting">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/43.gif" alt="hypnotized">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/44.gif" alt="liar">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/45.gif" alt="waiting">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/46.gif" alt="sigh">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/47.gif" alt="phbbbbt">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/48.gif" alt="cowboy">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/109.gif" alt="I dont want to see">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/110.gif" alt="hurry up!">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/111.gif" alt="rock on!">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/112.gif" alt="thumbs down">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/114.gif" alt="it wasnt me">',
'<img src="http://l.yimg.com/a/i/us/msg/emoticons/pirate_2.gif" alt="pirate*">',
'<img style="width: 31px; height: 18px;" src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/108.gif" alt="puppy dog eyes">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/106.gif" alt="I dont know">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/107.gif" alt="not listening">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/49.gif" alt="pig">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/50.gif" alt="cow">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/51.gif" alt="monkey">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/52.gif" alt="chicken">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/53.gif" alt="rose">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/54.gif" alt="good luck">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/55.gif" alt="flag">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/56.gif" alt="pumpkin">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/57.gif" alt="coffee">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/58.gif" alt="idea">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/59.gif" alt="skull">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/60.gif" alt="bug">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/61.gif" alt="alien">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/62.gif" alt="frustrated">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/63.gif" alt="praying">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/64.gif" alt="money eyes">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/65.gif" alt="whistling">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/66.gif" alt="feeling beat up">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/67.gif" alt="peace sign">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/68.gif" alt="shame on you">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/69.gif" alt="dancing">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/70.gif" alt="bring it on">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/71.gif" alt="hee hee">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/76.gif" alt="chatterbox">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/77.gif" alt="not worthy">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/78.gif" alt="oh go on">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/79.gif" alt="star">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/72.gif" alt="hiro">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/73.gif" alt="billy">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/74.gif" alt="april">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/75.gif" alt="yin yang">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/115.gif" alt="bee">',
'<img src="http://l.yimg.com/a/i/us/msg/emoticons/transformer.gif" alt="transformer*">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/4.gif" alt="big grin">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/3.gif" alt="winking">',
'<img style="width: 18px; height: 18px;" src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/1.gif" alt="happy">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/2.gif" alt="sad">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/15.gif" alt="smug">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/23.gif" alt="raised eyebrows">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/17.gif" alt="worried">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/10.gif" alt="tongue">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/39.gif" alt="thinking">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/13.gif" alt="surprise">',
'<img src="http://l.yimg.com/us.yimg.com/i/mesg/emoticons7/14.gif" alt="angry">'
);

public static $arraySmiley = array(
':-bd',
'&gt;:)',
';;)',
':((',
':))',
'&gt;:D&lt;',
':-/',
':x',
':&quot;&gt;',
':-*',
'=((',
'B-)',
'#:-S',
'/:)',
'=))',
'O:-)',
':-B',
'=;',
':-c',
':)]',
'~X(',
':-h',
':-t',
'8-&gt;',
'I-)',
'8-|',
'L-)',
':-&amp;',
':-$',
'[-(',
':O)',
'8-}',
'&lt;:-P',
'(:|',
'=P~',
'#-o',
'=D&gt;',
':-SS',
'@-)',
':^o',
':-w',
':-&lt;',
'&gt;:P',
'&lt;):)',
'X_X',
':!!',
'\m/',
':-q',
'^#(^',
':ar!',
':o3',
':-??',
'%-(',
':@)',
'3:-O',
':(|)',
'~:&gt;',
'@};-',
'%%-',
'**==',
'(~~)',
'~O)',
'*-:)',
'8-X',
'=:)',
'&gt;-)',
':-L',
'[-O&lt;',
'$-)',
':-&quot;',
'b-(',
':)&gt;-',
'[-X',
'\:D/',
'&gt;:/',
';))',
':-@',
'^:)^',
':-j',
'(*)',
'o-&gt;',
'o=&gt;',
'o-+',
'(%)',
':bz',
'[..]',
':D',
';)',
':)',
':(',
':&gt;',
':|',
':-S',
':P',
':-?',
':-O',
'X('
);


    public static function Convert($stringContent)
    {
        $result = str_ireplace(SmileyToImage::$arraySmiley, SmileyToImage::$arrayImage, $stringContent);
        return $result;
    }
}

?>